### ISSUE TITLE
Add local database to store scraped site text

### ISSUE THREAD

**Issue by Xyaneon** [Xyaneon/LTUAssistantPlus#24]
As part of #16, a local database will be needed to store scraped LTU website text gathered from #23. We may want to use a graph database for this; perhaps something like [Neo4j for Python](https://neo4j.com/developer/python/)?

**Comment by riooooorio** [comment]
@NeuralGirl  Hi, professor, 
Because there is no obvious relationships between each piece of data if we stored them into the Neo4j, which I though it's a waste of Neo4j's vision. The data from our Math Department is independent to each other, how do we come up with relationship to let them get linked?

**Comment by Xyaneon** [comment]
@riooooorio showed me the Neo4j database running from their desktop client. Perhaps we should look into the server version of it so the database can be run headless without manual user intervention. This would be more appropriate for using it as a dependency of another program IMO. I can try looking into that part later tonight or this weekend.

We might also need to get it working on Travis CI...
